opiproject/opi-prov-life

- examples/TELEGRAF.md
> enhance telegraf example to include more metrics

- README.md
from https://github.com/opiproject/opi-poc/pull/4
> Added contribution section to readme

- minutes/MeetingNotes - 12 Apr 2022.md
> add meeting notes

- examples/telegraf/Dockerfile.spdk
- examples/telegraf/README.md
- examples/telegraf/config/grafana-dashboard.json
- examples/telegraf/config/grafana-dashboards.yaml
- examples/telegraf/config/grafana-datasources.yml
- examples/telegraf/config/grafana.ini
- examples/telegraf/config/telegraf-spdk.conf
- examples/telegraf/docker-compose.yml
> example: enable to run telegraf automatically

- examples/hostmetricsreceiver/README.md
> example: add OTEL for Host Metrics Receiver

- minutes/MeetingNotes - 22 Feb 2022.md
- minutes/README.md
> Adding old meeting notes

- examples/telegraf/README.md
- examples/telegraf/config/telegraf-spdk.conf
> example: Add system monitoring to telegraf

- minutes/MeetingNotes - 26 Apr 2022.md
> adding meeting notes

- examples/telegraf/README.md
- examples/telegraf/docker-compose.yml
> example: Add healthchecks

- minutes/MeetingNotes - 12 Apr 2022.md
- minutes/MeetingNotes - 19 Apr 2022.md
> Fixing Anh Thu name

- minutes/MeetingNotes - 3 May 2022.md
> last meeting notes page

- .github/workflows/docker-publish.yml
- examples/telegraf/README.md
- examples/telegraf/docker-compose.yml
> ci: add qemu and docker-compose

- minutes/MeetingNotes - 10 May 2022.md
- minutes/MeetingNotes - 17 May 2022.md
> docs: update meeting notes

- USECASES.md
> Add use-cases first draft

- PROVISIONING.md
> add provisioning doc draft

- MONITORING.md
- PROVISIONING.md
- README.md
> small fixes

- INVENTORY.md
- PROVISIONING.md
- README.md
> add Inventory

- .github/workflows/docker-publish.yml
- examples/telegraf/Dockerfile.spdk
- examples/telegraf/docker-compose.yml
> examples: update SPDK and Fedora versions

- PROVISIONING.md
> minor fixes

- PROVISIONING.md
> provisioning: add some definitions

- .github/workflows/markdown.yml
- CHARTER.md
- MONITORING.md
- PROVISIONING.md
- README.md
- USECASES.md
> provisioning: add markdown linter checker

- examples/sztp/Dockerfile
- examples/sztp/README.md
- examples/sztp/docker-compose.yml
> examples: add sztp

- .github/workflows/markdown.yml
- examples/sztp/Dockerfile
> CI: add docekrfile hadolint

- ZTP.md
> udpate ZTP some more

- .github/dependabot.yml
- examples/sztp/Dockerfile
- examples/sztp/Dockerfile.client
- examples/sztp/Dockerfile.dhcp
- examples/sztp/Dockerfile.sztp
- examples/sztp/README.md
- examples/sztp/dhclient.conf
- examples/sztp/dhcpd.conf.template
- examples/sztp/docker-compose.yml
> dhcp: add custom options

- examples/sztp/Dockerfile.agent
- examples/sztp/Dockerfile.sztp
- examples/sztp/README.md
- examples/sztp/docker-compose.yml
- sztp: small rename
- Run rfc8572-agent.sh
> Run rfc8572-agent.sh

- examples/sztp/Dockerfile.sztp
- examples/sztp/README.md
- examples/sztp/docker-compose.yml
> sztp: automate boot

- examples/sztp/README.md
- examples/sztp/config/sztpd.running.json.template
- examples/sztp/docker-compose.yml
> sztp: actually download image and parse scripts

- .github/workflows/sztp-skip.yml
- .github/workflows/sztp.yml
- examples/sztp/README.md
- examples/sztp/tests.sh
> ci: add sztp tests

- .github/workflows/linters.yml
- README.md
- examples/sztp/tests.sh
- ci: add shellcheck
- ci: add dhcp test
> ci: add shellcheck and dhcp test

- ZTP.md
- examples/sztp/README.md
- examples/sztp/config/my-post-configuration-script.sh
- examples/sztp/config/my-pre-configuration-script.sh
- examples/sztp/docker-compose.yml
> ztp: small fixes

- examples/sztp/README.md
- examples/sztp/dhcpd.conf.template
> sztp: point sztp-redirect-urls in dhcp to bootstrap

- ZTP.md
> sztp: document sztp configuration steps by admin

- ZTP.md
- examples/sztp/README.md
- examples/sztp/config/sztpd.running.json.template
- examples/sztp/tests.sh
> sztp: add dhcp test and `download-uri` example 

- examples/sztp/tests.sh
> sztp: handle docker compose new plugin

- examples/sztp/.dockerignore
speed up builds and reduce image sizes
> ci: add .dockerignore

- ZTP.md
- sztp: add comment about ignoring dhcp options
- sztp: add device boostraping os before sztp
> sztp: add device boostraping os before sztp

- minutes/MeetingNotes - 23 Aug 2022.md
Minutes for meeting on 23rd August 2022
Based on my own notes.
Signed-off-by: Simon Horman <simon.horman@corigine.com>
> Minutes for meeting on 23rd August 2022

- examples/sztp/README.md
- examples/sztp/docker-compose.yml
> sztp: fix missing input.json

- examples/sztp/tests.sh
> ci: actually run and test scripts in ci

- examples/sztp/Dockerfile.agent
- examples/sztp/Dockerfile.bootstrap
> sztp: use WORKDIR instead of CD

- examples/sztp/README.md
- examples/sztp/docker-compose.yml
- examples/sztp/tests.sh
> sztp: auto-start with correct config

- examples/sztp/README.md
> sztp: remove obsolete doc portion

- examples/sztp/Dockerfile.agent
- examples/sztp/Dockerfile.bootstrap
> ci: reduce images size

- PROVISIONING.md
> ztp: readme cleanup

- examples/sztp/README.md
Signed-off-by: Kyle Mestery <mestery@mestery.com>
> Fix spelling

- BOOTSEQ.md
- README.md
> Add new Boot sequencing page

- BOOTSEQ.md
Signed-off-by: Shachar Tal <shachart@nvidia.com>
> expanding the boot sequence page

- INVENTORY.md
> Improve inventory documentation

- LIFECYCLE.md
Signed-off-by: Steven Royer <sroyer@redhat.com>
> Add lifecycle management requirements

- INVENTORY.md
Signed-off-by: Andrey Chilikin <andrey.chilikin@intel.com>
> add Intel dmidecode example

- COORDINATION.md
> Add IB and OOB

- COORDINATION.md
Made some minor wording tweaks.
> third option cleanups after offline feedback

- COORDINATION.md
Tweaks based on WG feedback. Also added comment on how idpf implements this
> Driver Ready Check tweaks 

- COORDINATION.md
Signed-off-by: Reza Bacchus <Reza.Bacchus@hpe.com>
> Add OOB USB2

- COORDINATION.md
Based on the comments from the earlier PR with comments from Marvell.
> Few more coordination tweaks

- COORDINATION.md
> add ARM assumption

- vendors/marvell/survey_2_17_2023_responses
Marvell responses to survey from 2/17/2023.
> Create file survey_2_17_2023_responses

- README.md
Add Gal as leader of the Lifecycle and Provisioning WG.
Signed-off-by: Paul Pindell <ppindell@gmail.com>
> Update README.md with Gal as leader
